name: Sequentially Jobs
on: workflow_dispatch
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build steps
              run: echo "Build steps"
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Test steps
              run: echo "Test steps"
    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Deploy steps
              run: echo "Deploy steps"