name: Push Trigger
on:
    push:
        branches:
            - main
            - develop
            - 'release/**'
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Simple steps
              run: echo "Hello World"