name: Action
on: workflow_dispatch
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Print index.html
              run: cat index.html